#!/usr/bin/env perl

use 5.010001;
use strict;
use warnings;
use Log::ger;
use Log::ger::Level::trace;

use DBIx::Connect::MySQL;
use POSIX qw(strftime);

my $src = "YF"; # yahoo finance

my $dbh = DBIx::Connect::MySQL->connect(
    "dbi:mysql:database=sero", undef, undef, {RaiseError=>1});

my ($exchange_id) =
    $dbh->selectrow_array("SELECT id FROM exchange WHERE code='IDX'");
die unless $exchange_id;

my $sth = $dbh->prepare("
INSERT INTO daily_price (
  src, exchange_id, date, code,
  open,high,low,close,
  adjclose,
  volume)
VALUES (
  ?, ?, ?, ?,
  ?,?,?,?,
  ?,
  ?
)
");

for my $file (<*.csv>) {
    my ($code) = $file =~ /(.+).csv/;
    $code =~ s/\.JK$//;
    next unless $code =~ /^\^?\w{4}$/;

    $code = "COMPOSITE" if $code eq '^JKSE';

    warn "Processing '$file' ...\n";
    open my $fh, "<", $file or die;

    my $i = 0;
    while (<$fh>) {
        next unless $i++;
        chomp;
        my @F = split/,/,$_;
        $F[0] =~ s!/!-!g;
        $sth->execute(
            $src, $exchange_id, $F[0], $code,
            $F[1], $F[2], $F[3], $F[4],
            $F[6],
            $F[5],
        );
    }
}
